import { HardwareConfig } from '../types';

export function generateArduinoFirmware(config: HardwareConfig): string {
  const x1 = config.xPins[0];
  const x2 = config.xPins[1];
  const x3 = config.xPins[2];
  const x4 = config.xPins[3];

  const y1 = config.yPins[0];
  const y2 = config.yPins[1];
  const y3 = config.yPins[2];
  const y4 = config.yPins[3];

  const servoPin = config.penServoPin;
  const penUp = config.penUpAngle;
  const penDown = config.penDownAngle;
  const stepsPerMmX = config.stepsPerMmX.toFixed(2);
  const stepsPerMmY = config.stepsPerMmY.toFixed(2);
  const invertX = config.invertX ? -1 : 1;
  const invertY = config.invertY ? -1 : 1;
  const isHalfStep = config.stepMode === 'half_step';

  return `/*
 * =====================================================================
 *  Explore CNC - 2D Pen Plotter Firmware for Arduino
 *  Microcontroller: Arduino ${config.arduinoModel.toUpperCase()}
 *  Motors: 28BYJ-48 5V Stepper Motors (Gear Ratio 1:64)
 *  Driver Boards: Dual ULN2003 Darlington Transistor Arrays
 *  Pen Mechanism: SG90 Micro Servo
 * =====================================================================
 *  Generated by Explore CNC Web Application
 *  Compatible with Arduino Uno, Nano, Mega, and CNC Web Controller
 * =====================================================================
 */

#include <Servo.h>

// --- PIN DEFINITIONS FOR ULN2003 DRIVERS ---
// X-Axis ULN2003 Stepper Driver (IN1, IN2, IN3, IN4)
const int PIN_X1 = ${x1};
const int PIN_X2 = ${x2};
const int PIN_X3 = ${x3};
const int PIN_X4 = ${x4};

// Y-Axis ULN2003 Stepper Driver (IN1, IN2, IN3, IN4)
const int PIN_Y1 = ${y1};
const int PIN_Y2 = ${y2};
const int PIN_Y3 = ${y3};
const int PIN_Y4 = ${y4};

// Pen Lift Servo (PWM Pin)
const int PIN_SERVO = ${servoPin};

// --- CALIBRATION & KINEMATICS ---
const float STEPS_PER_MM_X = ${stepsPerMmX}; // 28BYJ-48 steps per mm (${config.driveMechanism})
const float STEPS_PER_MM_Y = ${stepsPerMmY};
const int DIR_X = ${invertX};
const int DIR_Y = ${invertY};

// Pen Servo Angles (Degrees 0 - 180)
const int PEN_UP_ANGLE = ${penUp};
const int PEN_DOWN_ANGLE = ${penDown};
const int SERVO_LIFT_DELAY_MS = 180;

// Maximum step speed (microseconds delay per step)
// 28BYJ-48 stepper motors run reliably between 1000us - 2500us delay
const unsigned int MIN_STEP_DELAY_US = 1200; 

// 28BYJ-48 8-Step Half-Stepping Sequence (Smoother, higher torque, 4096 steps/rev)
${
  isHalfStep
    ? `const int STEP_SEQUENCE[8][4] = {
  {HIGH, LOW,  LOW,  LOW }, // Step 0
  {HIGH, HIGH, LOW,  LOW }, // Step 1
  {LOW,  HIGH, LOW,  LOW }, // Step 2
  {LOW,  HIGH, HIGH, LOW }, // Step 3
  {LOW,  LOW,  HIGH, LOW }, // Step 4
  {LOW,  LOW,  HIGH, HIGH}, // Step 5
  {LOW,  LOW,  LOW,  HIGH}, // Step 6
  {HIGH, LOW,  LOW,  HIGH}  // Step 7
};
const int TOTAL_SEQUENCE_STEPS = 8;`
    : `const int STEP_SEQUENCE[4][4] = {
  {HIGH, HIGH, LOW,  LOW }, // Phase A
  {LOW,  HIGH, HIGH, LOW }, // Phase B
  {LOW,  LOW,  HIGH, HIGH}, // Phase C
  {HIGH, LOW,  LOW,  HIGH}  // Phase D
};
const int TOTAL_SEQUENCE_STEPS = 4;`
}

// Global System State
Servo penServo;
long currentStepX = 0;
long currentStepY = 0;
float currentMmX = 0.0;
float currentMmY = 0.0;
int currentStepIndexX = 0;
int currentStepIndexY = 0;
bool isPenDown = false;
bool isAbsoluteMode = true;

// Serial Command Buffer
String inputBuffer = "";
bool commandReady = false;

void setup() {
  Serial.begin(${config.baudRate});
  while (!Serial) { ; } // Wait for serial port

  // Setup ULN2003 Output Pins for X
  pinMode(PIN_X1, OUTPUT);
  pinMode(PIN_X2, OUTPUT);
  pinMode(PIN_X3, OUTPUT);
  pinMode(PIN_X4, OUTPUT);

  // Setup ULN2003 Output Pins for Y
  pinMode(PIN_Y1, OUTPUT);
  pinMode(PIN_Y2, OUTPUT);
  pinMode(PIN_Y3, OUTPUT);
  pinMode(PIN_Y4, OUTPUT);

  // De-energize coils initially to avoid heating
  disableMotors();

  // Attach Pen Servo
  penServo.attach(PIN_SERVO);
  setPen(false); // Start with pen UP

  Serial.println(F("ExploreCNC Ready (28BYJ-48 + ULN2003)"));
  Serial.println(F("Firmware: v2.4"));
  Serial.println(F("ok"));
}

void loop() {
  // Read serial input non-blockingly
  while (Serial.available() > 0) {
    char c = (char)Serial.read();
    if (c == '\\n' || c == '\\r') {
      if (inputBuffer.length() > 0) {
        commandReady = true;
        break;
      }
    } else {
      inputBuffer += c;
    }
  }

  if (commandReady) {
    processGCode(inputBuffer);
    inputBuffer = "";
    commandReady = false;
    Serial.println(F("ok"));
  }
}

// De-energizes ULN2003 driver pins to keep 28BYJ-48 coils cool when stopped
void disableMotors() {
  digitalWrite(PIN_X1, LOW);
  digitalWrite(PIN_X2, LOW);
  digitalWrite(PIN_X3, LOW);
  digitalWrite(PIN_X4, LOW);

  digitalWrite(PIN_Y1, LOW);
  digitalWrite(PIN_Y2, LOW);
  digitalWrite(PIN_Y3, LOW);
  digitalWrite(PIN_Y4, LOW);
}

// Moves X axis by one step (+1 forward, -1 backward)
void stepMotorX(int direction) {
  currentStepIndexX = (currentStepIndexX + (direction * DIR_X) + TOTAL_SEQUENCE_STEPS) % TOTAL_SEQUENCE_STEPS;
  digitalWrite(PIN_X1, STEP_SEQUENCE[currentStepIndexX][0]);
  digitalWrite(PIN_X2, STEP_SEQUENCE[currentStepIndexX][1]);
  digitalWrite(PIN_X3, STEP_SEQUENCE[currentStepIndexX][2]);
  digitalWrite(PIN_X4, STEP_SEQUENCE[currentStepIndexX][3]);
  currentStepX += direction;
}

// Moves Y axis by one step (+1 forward, -1 backward)
void stepMotorY(int direction) {
  currentStepIndexY = (currentStepIndexY + (direction * DIR_Y) + TOTAL_SEQUENCE_STEPS) % TOTAL_SEQUENCE_STEPS;
  digitalWrite(PIN_Y1, STEP_SEQUENCE[currentStepIndexY][0]);
  digitalWrite(PIN_Y2, STEP_SEQUENCE[currentStepIndexY][1]);
  digitalWrite(PIN_Y3, STEP_SEQUENCE[currentStepIndexY][2]);
  digitalWrite(PIN_Y4, STEP_SEQUENCE[currentStepIndexY][3]);
  currentStepY += direction;
}

// Raises or lowers pen servo
void setPen(bool down) {
  if (down == isPenDown) return;
  isPenDown = down;
  penServo.write(down ? PEN_DOWN_ANGLE : PEN_UP_ANGLE);
  delay(SERVO_LIFT_DELAY_MS);
}

// Bresenham Linear Interpolation Algorithm for synchronous 2D drawing
void moveLine(float targetMmX, float targetMmY, unsigned int stepDelayUs) {
  long targetStepX = lround(targetMmX * STEPS_PER_MM_X);
  long targetStepY = lround(targetMmY * STEPS_PER_MM_Y);

  long deltaX = targetStepX - currentStepX;
  long deltaY = targetStepY - currentStepY;

  int dirX = (deltaX > 0) ? 1 : (deltaX < 0) ? -1 : 0;
  int dirY = (deltaY > 0) ? 1 : (deltaY < 0) ? -1 : 0;

  long absDeltaX = abs(deltaX);
  long absDeltaY = abs(deltaY);

  long error = 0;

  if (absDeltaX >= absDeltaY) {
    // X is primary driving axis
    error = absDeltaX / 2;
    for (long i = 0; i < absDeltaX; i++) {
      stepMotorX(dirX);
      error -= absDeltaY;
      if (error < 0) {
        stepMotorY(dirY);
        error += absDeltaX;
      }
      delayMicroseconds(stepDelayUs);
    }
  } else {
    // Y is primary driving axis
    error = absDeltaY / 2;
    for (long i = 0; i < absDeltaY; i++) {
      stepMotorY(dirY);
      error -= absDeltaX;
      if (error < 0) {
        stepMotorX(dirX);
        error += absDeltaY;
      }
      delayMicroseconds(stepDelayUs);
    }
  }

  currentMmX = targetMmX;
  currentMmY = targetMmY;
}

// Parses and executes standard CNC G-code commands
void processGCode(String cmd) {
  cmd.trim();
  if (cmd.length() == 0 || cmd.startsWith(";") || cmd.startsWith("(")) return;

  // Remove trailing inline comments
  int commentIdx = cmd.indexOf(';');
  if (commentIdx > 0) cmd = cmd.substring(0, commentIdx);
  cmd.trim();

  // Parse G0/G1 Linear Motion
  if (cmd.startsWith("G0") || cmd.startsWith("G1") || cmd.startsWith("G00") || cmd.startsWith("G01")) {
    bool isRapid = cmd.startsWith("G0 ") || cmd.startsWith("G00 ") || cmd.equals("G0") || cmd.equals("G00");
    float targetX = currentMmX;
    float targetY = currentMmY;

    int xIdx = cmd.indexOf('X');
    if (xIdx != -1) {
      targetX = parseNumber(cmd, xIdx + 1);
      if (!isAbsoluteMode) targetX += currentMmX;
    }

    int yIdx = cmd.indexOf('Y');
    if (yIdx != -1) {
      targetY = parseNumber(cmd, yIdx + 1);
      if (!isAbsoluteMode) targetY += currentMmY;
    }

    // Check for optional inline Z or pen flag
    int zIdx = cmd.indexOf('Z');
    if (zIdx != -1) {
      float zVal = parseNumber(cmd, zIdx + 1);
      setPen(zVal <= 0.0);
    }

    unsigned int stepDelay = isRapid ? MIN_STEP_DELAY_US : (MIN_STEP_DELAY_US + 400);
    moveLine(targetX, targetY, stepDelay);
  }
  // G28: Return to Home
  else if (cmd.startsWith("G28")) {
    setPen(false);
    moveLine(0.0, 0.0, MIN_STEP_DELAY_US);
    currentStepX = 0;
    currentStepY = 0;
    currentMmX = 0.0;
    currentMmY = 0.0;
  }
  // G90: Absolute Positioning
  else if (cmd.startsWith("G90")) {
    isAbsoluteMode = true;
  }
  // G91: Relative Positioning
  else if (cmd.startsWith("G91")) {
    isAbsoluteMode = false;
  }
  // G92: Set Zero Coordinates
  else if (cmd.startsWith("G92")) {
    currentStepX = 0;
    currentStepY = 0;
    currentMmX = 0.0;
    currentMmY = 0.0;
  }
  // M300: Servo Angle or Pen State (M300 S<angle>)
  else if (cmd.startsWith("M300")) {
    int sIdx = cmd.indexOf('S');
    if (sIdx != -1) {
      int angle = parseNumber(cmd, sIdx + 1);
      penServo.write(constrain(angle, 0, 180));
      delay(SERVO_LIFT_DELAY_MS);
      isPenDown = (angle <= PEN_DOWN_ANGLE + 5);
    }
  }
  // M3 / M03: Pen Down
  else if (cmd.startsWith("M3") || cmd.startsWith("M03")) {
    setPen(true);
  }
  // M5 / M05: Pen Up
  else if (cmd.startsWith("M5") || cmd.startsWith("M05")) {
    setPen(false);
  }
  // M114: Report Position
  else if (cmd.startsWith("M114")) {
    Serial.print(F("X:"));
    Serial.print(currentMmX, 2);
    Serial.print(F(" Y:"));
    Serial.print(currentMmY, 2);
    Serial.print(F(" Pen:"));
    Serial.println(isPenDown ? F("DOWN") : F("UP"));
  }
  // M18 / M84: Turn off stepper driver coils (protects 28BYJ-48 from heat)
  else if (cmd.startsWith("M18") || cmd.startsWith("M84")) {
    disableMotors();
  }
  // M112: Emergency Stop
  else if (cmd.startsWith("M112")) {
    setPen(false);
    disableMotors();
    Serial.println(F("!! EMERGENCY STOP TRIGGERED !!"));
  }
}

// Extracts a floating point number from command string
float parseNumber(String str, int startIdx) {
  int endIdx = startIdx;
  while (endIdx < str.length() && 
        (isDigit(str.charAt(endIdx)) || str.charAt(endIdx) == '.' || str.charAt(endIdx) == '-')) {
    endIdx++;
  }
  return str.substring(startIdx, endIdx).toFloat();
}
`;
}

export function generateEsp32Firmware(config: HardwareConfig): string {
  const x1 = config.xPins[0];
  const x2 = config.xPins[1];
  const x3 = config.xPins[2];
  const x4 = config.xPins[3];

  const y1 = config.yPins[0];
  const y2 = config.yPins[1];
  const y3 = config.yPins[2];
  const y4 = config.yPins[3];

  const servoPin = config.penServoPin;
  const penUp = config.penUpAngle;
  const penDown = config.penDownAngle;
  const stepsPerMmX = config.stepsPerMmX.toFixed(2);
  const stepsPerMmY = config.stepsPerMmY.toFixed(2);
  const invertX = config.invertX ? -1 : 1;
  const invertY = config.invertY ? -1 : 1;
  const isHalfStep = config.stepMode === 'half_step';

  return `/*
 * =====================================================================
 *  Explore CNC - Dual USB & Wi-Fi Pen Plotter Firmware for ESP32
 *  Microcontroller: ESP32 DevKit V1 / ESP32-WROOM-32
 *  Motors: 28BYJ-48 5V Stepper Motors (Gear Ratio 1:64)
 *  Driver Boards: Dual ULN2003 Darlington Transistor Arrays
 *  Pen Mechanism: SG90 Micro Servo (ESP32Servo PWM)
 * =====================================================================
 *  Features:
 *   - High-Speed USB Serial G-Code Streaming (115200 Baud)
 *   - Standalone Wi-Fi Access Point ("${config.wifiSsid}") + WebSockets
 *   - Non-blocking Bresenham Line Stepping
 *   - Auto-Coil Sleep (protects 28BYJ-48 motors from heat)
 * =====================================================================
 */

#include <WiFi.h>
#include <WebServer.h>
#include <WebSocketsServer.h>
#include <ESP32Servo.h>

// --- PIN DEFINITIONS FOR ULN2003 DRIVERS ---
// X-Axis ULN2003 Stepper Driver (IN1, IN2, IN3, IN4)
const int PIN_X1 = ${x1};
const int PIN_X2 = ${x2};
const int PIN_X3 = ${x3};
const int PIN_X4 = ${x4};

// Y-Axis ULN2003 Stepper Driver (IN1, IN2, IN3, IN4)
const int PIN_Y1 = ${y1};
const int PIN_Y2 = ${y2};
const int PIN_Y3 = ${y3};
const int PIN_Y4 = ${y4};

// Pen Lift Servo (PWM Pin)
const int PIN_SERVO = ${servoPin};

// --- WI-FI SETTINGS ---
const char* AP_SSID = "${config.wifiSsid}";
const char* AP_PASS = "${config.wifiPassword || 'plotter123'}";

WebServer server(${config.webServerPort});
WebSocketsServer webSocket = WebSocketsServer(${config.wsServerPort});

// --- KINEMATICS & 28BYJ-48 PARAMETERS ---
const float STEPS_PER_MM_X = ${stepsPerMmX}; // 28BYJ-48 steps per mm (${config.driveMechanism})
const float STEPS_PER_MM_Y = ${stepsPerMmY};
const int DIR_X = ${invertX};
const int DIR_Y = ${invertY};

// Pen Servo Angles
const int PEN_UP_ANGLE = ${penUp};
const int PEN_DOWN_ANGLE = ${penDown};
const int SERVO_LIFT_DELAY_MS = 160;

// Delay between steps (micro-seconds)
const unsigned int MIN_STEP_DELAY_US = 1100;

// 28BYJ-48 8-Step Half-Stepping Table (ULN2003 Darlington Array)
${
  isHalfStep
    ? `const int STEP_SEQUENCE[8][4] = {
  {1, 0, 0, 0},
  {1, 1, 0, 0},
  {0, 1, 0, 0},
  {0, 1, 1, 0},
  {0, 0, 1, 0},
  {0, 0, 1, 1},
  {0, 0, 0, 1},
  {1, 0, 0, 1}
};
const int TOTAL_SEQUENCE_STEPS = 8;`
    : `const int STEP_SEQUENCE[4][4] = {
  {1, 1, 0, 0},
  {0, 1, 1, 0},
  {0, 0, 1, 1},
  {1, 0, 0, 1}
};
const int TOTAL_SEQUENCE_STEPS = 4;`
}

// Global Coordinates and Machine State
Servo penServo;
long currentStepX = 0;
long currentStepY = 0;
float currentMmX = 0.0;
float currentMmY = 0.0;
int currentStepIndexX = 0;
int currentStepIndexY = 0;
bool isPenDown = false;
bool isAbsoluteMode = true;
String serialBuffer = "";

void setup() {
  Serial.begin(${config.baudRate});
  delay(100);

  // Setup GPIOs for X ULN2003
  pinMode(PIN_X1, OUTPUT);
  pinMode(PIN_X2, OUTPUT);
  pinMode(PIN_X3, OUTPUT);
  pinMode(PIN_X4, OUTPUT);

  // Setup GPIOs for Y ULN2003
  pinMode(PIN_Y1, OUTPUT);
  pinMode(PIN_Y2, OUTPUT);
  pinMode(PIN_Y3, OUTPUT);
  pinMode(PIN_Y4, OUTPUT);

  disableMotors();

  // Setup Servo using ESP32 PWM timer
  ESP32PWM::allocateTimer(0);
  penServo.setPeriodHertz(50);
  penServo.attach(PIN_SERVO, 500, 2400);
  setPen(false);

  // Setup Wi-Fi Access Point & WebSockets
  WiFi.softAP(AP_SSID, AP_PASS);
  IPAddress IP = WiFi.softAPIP();
  Serial.print(F("ExploreCNC AP Started. IP Address: "));
  Serial.println(IP);

  // HTTP Endpoints
  server.on("/api/telemetry", HTTP_GET, handleTelemetry);
  server.on("/api/command", HTTP_POST, handleCommand);
  server.begin();

  // WebSocket Server
  webSocket.begin();
  webSocket.onEvent(webSocketEvent);

  Serial.println(F("ExploreCNC ESP32 Firmware Ready (28BYJ-48 + ULN2003)"));
  Serial.println(F("ok"));
}

void loop() {
  server.handleClient();
  webSocket.loop();

  // Serial Stream Handling
  while (Serial.available() > 0) {
    char c = (char)Serial.read();
    if (c == '\\n' || c == '\\r') {
      if (serialBuffer.length() > 0) {
        processGCode(serialBuffer);
        serialBuffer = "";
        Serial.println(F("ok"));
      }
    } else {
      serialBuffer += c;
    }
  }
}

// Broadcasts status telemetry JSON
void handleTelemetry() {
  String json = "{\\"state\\":\\"IDLE\\",\\"x\\":" + String(currentMmX, 2) + 
                ",\\"y\\":" + String(currentMmY, 2) + 
                ",\\"pen\\":\\"" + (isPenDown ? "DOWN" : "UP") + "\\"}";
  server.send(200, "application/json", json);
}

void handleCommand() {
  if (server.hasArg("plain")) {
    String gcode = server.arg("plain");
    processGCode(gcode);
    server.send(200, "text/plain", "ok\\n");
  } else {
    server.send(400, "text/plain", "Missing body\\n");
  }
}

void webSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length) {
  if (type == WStype_TEXT) {
    String cmd = String((char*)payload);
    processGCode(cmd);
    webSocket.sendTXT(num, "ok");
  }
}

// Turns off all ULN2003 coils to prevent motor heating
void disableMotors() {
  digitalWrite(PIN_X1, LOW);
  digitalWrite(PIN_X2, LOW);
  digitalWrite(PIN_X3, LOW);
  digitalWrite(PIN_X4, LOW);

  digitalWrite(PIN_Y1, LOW);
  digitalWrite(PIN_Y2, LOW);
  digitalWrite(PIN_Y3, LOW);
  digitalWrite(PIN_Y4, LOW);
}

void stepMotorX(int direction) {
  currentStepIndexX = (currentStepIndexX + (direction * DIR_X) + TOTAL_SEQUENCE_STEPS) % TOTAL_SEQUENCE_STEPS;
  digitalWrite(PIN_X1, STEP_SEQUENCE[currentStepIndexX][0]);
  digitalWrite(PIN_X2, STEP_SEQUENCE[currentStepIndexX][1]);
  digitalWrite(PIN_X3, STEP_SEQUENCE[currentStepIndexX][2]);
  digitalWrite(PIN_X4, STEP_SEQUENCE[currentStepIndexX][3]);
  currentStepX += direction;
}

void stepMotorY(int direction) {
  currentStepIndexY = (currentStepIndexY + (direction * DIR_Y) + TOTAL_SEQUENCE_STEPS) % TOTAL_SEQUENCE_STEPS;
  digitalWrite(PIN_Y1, STEP_SEQUENCE[currentStepIndexY][0]);
  digitalWrite(PIN_Y2, STEP_SEQUENCE[currentStepIndexY][1]);
  digitalWrite(PIN_Y3, STEP_SEQUENCE[currentStepIndexY][2]);
  digitalWrite(PIN_Y4, STEP_SEQUENCE[currentStepIndexY][3]);
  currentStepY += direction;
}

void setPen(bool down) {
  if (down == isPenDown) return;
  isPenDown = down;
  penServo.write(down ? PEN_DOWN_ANGLE : PEN_UP_ANGLE);
  delay(SERVO_LIFT_DELAY_MS);
}

void moveLine(float targetMmX, float targetMmY, unsigned int stepDelayUs) {
  long targetStepX = lround(targetMmX * STEPS_PER_MM_X);
  long targetStepY = lround(targetMmY * STEPS_PER_MM_Y);

  long deltaX = targetStepX - currentStepX;
  long deltaY = targetStepY - currentStepY;

  int dirX = (deltaX > 0) ? 1 : (deltaX < 0) ? -1 : 0;
  int dirY = (deltaY > 0) ? 1 : (deltaY < 0) ? -1 : 0;

  long absDeltaX = abs(deltaX);
  long absDeltaY = abs(deltaY);

  long error = 0;

  if (absDeltaX >= absDeltaY) {
    error = absDeltaX / 2;
    for (long i = 0; i < absDeltaX; i++) {
      stepMotorX(dirX);
      error -= absDeltaY;
      if (error < 0) {
        stepMotorY(dirY);
        error += absDeltaX;
      }
      delayMicroseconds(stepDelayUs);
    }
  } else {
    error = absDeltaY / 2;
    for (long i = 0; i < absDeltaY; i++) {
      stepMotorY(dirY);
      error -= absDeltaX;
      if (error < 0) {
        stepMotorX(dirX);
        error += absDeltaY;
      }
      delayMicroseconds(stepDelayUs);
    }
  }

  currentMmX = targetMmX;
  currentMmY = targetMmY;
}

void processGCode(String cmd) {
  cmd.trim();
  if (cmd.length() == 0 || cmd.startsWith(";") || cmd.startsWith("(")) return;

  int commentIdx = cmd.indexOf(';');
  if (commentIdx > 0) cmd = cmd.substring(0, commentIdx);
  cmd.trim();

  if (cmd.startsWith("G0") || cmd.startsWith("G1") || cmd.startsWith("G00") || cmd.startsWith("G01")) {
    bool isRapid = cmd.startsWith("G0 ") || cmd.startsWith("G00 ") || cmd.equals("G0") || cmd.equals("G00");
    float targetX = currentMmX;
    float targetY = currentMmY;

    int xIdx = cmd.indexOf('X');
    if (xIdx != -1) {
      targetX = parseNumber(cmd, xIdx + 1);
      if (!isAbsoluteMode) targetX += currentMmX;
    }

    int yIdx = cmd.indexOf('Y');
    if (yIdx != -1) {
      targetY = parseNumber(cmd, yIdx + 1);
      if (!isAbsoluteMode) targetY += currentMmY;
    }

    int zIdx = cmd.indexOf('Z');
    if (zIdx != -1) {
      float zVal = parseNumber(cmd, zIdx + 1);
      setPen(zVal <= 0.0);
    }

    unsigned int stepDelay = isRapid ? MIN_STEP_DELAY_US : (MIN_STEP_DELAY_US + 300);
    moveLine(targetX, targetY, stepDelay);
  }
  else if (cmd.startsWith("G28")) {
    setPen(false);
    moveLine(0.0, 0.0, MIN_STEP_DELAY_US);
    currentStepX = 0;
    currentStepY = 0;
    currentMmX = 0.0;
    currentMmY = 0.0;
  }
  else if (cmd.startsWith("G90")) {
    isAbsoluteMode = true;
  }
  else if (cmd.startsWith("G91")) {
    isAbsoluteMode = false;
  }
  else if (cmd.startsWith("G92")) {
    currentStepX = 0;
    currentStepY = 0;
    currentMmX = 0.0;
    currentMmY = 0.0;
  }
  else if (cmd.startsWith("M300")) {
    int sIdx = cmd.indexOf('S');
    if (sIdx != -1) {
      int angle = parseNumber(cmd, sIdx + 1);
      penServo.write(constrain(angle, 0, 180));
      delay(SERVO_LIFT_DELAY_MS);
      isPenDown = (angle <= PEN_DOWN_ANGLE + 5);
    }
  }
  else if (cmd.startsWith("M3") || cmd.startsWith("M03")) {
    setPen(true);
  }
  else if (cmd.startsWith("M5") || cmd.startsWith("M05")) {
    setPen(false);
  }
  else if (cmd.startsWith("M114")) {
    Serial.print(F("X:"));
    Serial.print(currentMmX, 2);
    Serial.print(F(" Y:"));
    Serial.print(currentMmY, 2);
    Serial.print(F(" Pen:"));
    Serial.println(isPenDown ? F("DOWN") : F("UP"));
  }
  else if (cmd.startsWith("M18") || cmd.startsWith("M84")) {
    disableMotors();
  }
  else if (cmd.startsWith("M112")) {
    setPen(false);
    disableMotors();
    Serial.println(F("!! EMERGENCY STOP TRIGGERED !!"));
  }
}

float parseNumber(String str, int startIdx) {
  int endIdx = startIdx;
  while (endIdx < str.length() && 
        (isDigit(str.charAt(endIdx)) || str.charAt(endIdx) == '.' || str.charAt(endIdx) == '-')) {
    endIdx++;
  }
  return str.substring(startIdx, endIdx).toFloat();
}
`;
}
